CREATE TABLE executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    job_id BIGINT NOT NULL,

    status VARCHAR(20) NOT NULL,

    command TEXT NOT NULL,
    max_retries INTEGER NOT NULL,
    timeout_seconds INTEGER NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,

    exit_code INTEGER,
    error_message TEXT,

    CONSTRAINT executions_job_fk
        FOREIGN KEY (job_id)
        REFERENCES jobs(id),

    CONSTRAINT executions_status_check
        CHECK (status IN (
            'QUEUED',
            'RUNNING',
            'SUCCEEDED',
            'FAILED',
            'CANCELLED'
        )),

    CONSTRAINT executions_max_retries_check
        CHECK (max_retries >= 0),

    CONSTRAINT executions_timeout_seconds_check
        CHECK (timeout_seconds > 0)
);

CREATE INDEX idx_executions_job_id
    ON executions(job_id);