spring.application.name=orbit-server

spring.datasource.url=jdbc:postgresql://localhost:5432/orbit
spring.datasource.username=orbit
spring.datasource.password=orbit

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.open-in-view=false